replicaCount: 1

namespace: "oaicicd-tmp"

image:
  registry: local
  repository: tolgaomeratalay/gnbsim
  version: "4.3"
  pullPolicy: Always

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: "oai-gnbsim-sa14"

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

securityContext:
  privileged: true

service:
  type: ClusterIP
  http1Port: 80

start:
  gnbsim: true

multus:
  ngapIPadd: "192.168.16.14"
  ngapNetmask: "16"
  ngapGateway: "192.168.10.1"
  gtpIPadd: "192.168.17.14"
  gtpNetmask: "16"
  gtpGateway: "192.168.10.1"

config:
  mcc: "208"
  mnc: "95"
  gnbid: "14"
  tac: "0x00a000"
  sst: "222"
  sd: "00007b"
  pagingdrx: "v32"
  ranuengapid: "0"
  imeisv: "35609204079514"
  msin: "1000000014"
  routingindicator: "1234"
  protectionscheme: "null"
  key: "0C1A34601D4F07677303652C04625014"
  opc: "63bfa50ee6523365ff14c1f45f88737d"
  dnn: "default"
  url: "http://192.168.76.205:8000"
  nrcellid: "1"
  ngappeeraddr: "192.168.12.10"
  gtpulocaladdr: "192.168.16.14"
  gtpuifname: "net2"
  usefqdn: "no"
persistence:
  enabled: false

resources: 
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
